/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventManagementRouteImport } from './routes/event-management'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as BookingEventIdRouteImport } from './routes/booking.$eventId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrganisersRouteImport } from './routes/admin/organisers'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminEditEventEventIdRouteImport } from './routes/admin/edit-event.$eventId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventManagementRoute = EventManagementRouteImport.update({
  id: '/event-management',
  path: '/event-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const BookingEventIdRoute = BookingEventIdRouteImport.update({
  id: '/booking/$eventId',
  path: '/booking/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganisersRoute = AdminOrganisersRouteImport.update({
  id: '/admin/organisers',
  path: '/admin/organisers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditEventEventIdRoute = AdminEditEventEventIdRouteImport.update({
  id: '/admin/edit-event/$eventId',
  path: '/admin/edit-event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-event': typeof CreateEventRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organisers': typeof AdminOrganisersRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$eventId': typeof BookingEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-event/$eventId': typeof AdminEditEventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-event': typeof CreateEventRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organisers': typeof AdminOrganisersRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$eventId': typeof BookingEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit-event/$eventId': typeof AdminEditEventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-event': typeof CreateEventRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organisers': typeof AdminOrganisersRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$eventId': typeof BookingEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-event/$eventId': typeof AdminEditEventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/create-event'
    | '/event-management'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/organisers'
    | '/admin/users'
    | '/booking/$eventId'
    | '/events/$eventId'
    | '/admin/'
    | '/admin/edit-event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/create-event'
    | '/event-management'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/organisers'
    | '/admin/users'
    | '/booking/$eventId'
    | '/events/$eventId'
    | '/admin'
    | '/admin/edit-event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/create-event'
    | '/event-management'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/organisers'
    | '/admin/users'
    | '/booking/$eventId'
    | '/events/$eventId'
    | '/admin/'
    | '/admin/edit-event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreateEventRoute: typeof CreateEventRoute
  EventManagementRoute: typeof EventManagementRoute
  EventsRoute: typeof EventsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrganisersRoute: typeof AdminOrganisersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BookingEventIdRoute: typeof BookingEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditEventEventIdRoute: typeof AdminEditEventEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-management': {
      id: '/event-management'
      path: '/event-management'
      fullPath: '/event-management'
      preLoaderRoute: typeof EventManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/booking/$eventId': {
      id: '/booking/$eventId'
      path: '/booking/$eventId'
      fullPath: '/booking/$eventId'
      preLoaderRoute: typeof BookingEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organisers': {
      id: '/admin/organisers'
      path: '/admin/organisers'
      fullPath: '/admin/organisers'
      preLoaderRoute: typeof AdminOrganisersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-event/$eventId': {
      id: '/admin/edit-event/$eventId'
      path: '/admin/edit-event/$eventId'
      fullPath: '/admin/edit-event/$eventId'
      preLoaderRoute: typeof AdminEditEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreateEventRoute: CreateEventRoute,
  EventManagementRoute: EventManagementRoute,
  EventsRoute: EventsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrganisersRoute: AdminOrganisersRoute,
  AdminUsersRoute: AdminUsersRoute,
  BookingEventIdRoute: BookingEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditEventEventIdRoute: AdminEditEventEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
